# Generated by Django 3.0 on 2019-12-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolLibrary', '0004_auto_20191211_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
