# Generated by Django 3.0 on 2019-12-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolLibrary', '0006_auto_20191212_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
