# Generated by Django 3.0 on 2019-12-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolLibrary', '0008_auto_20191212_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='date_of_loan',
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_loan', models.DateTimeField(verbose_name='Date of Loan')),
                ('loan_date_expire', models.DateTimeField(verbose_name='Loan End Date')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolLibrary.Loan')),
            ],
        ),
    ]
