name: DEPLOY

on: [create]

jobs:
  build:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v1
        
      - name: Deploy to Heroku
        env:
          HEROKU_API_TOKEN: "db7d630c-7fe3-4f4b-a134-2f4c34cc711d"
          HEROKU_APP_NAME: "thecoolibrary"
        #if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
        
        #run: echo "result = $((github.ref == 'refs/heads/master')) , $((job.status == 'success'))"
