name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install --user --updrade pipenv
        pipenv install
        pipenv shell
    - name: Update Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Test with Django tests
      run: |
        python manage.py test polls
        
