name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        python3 -m pip install --upgrade pip
        brew install pipenv
        pipenv install
    - name: Update Migrations
      run: |
        ls
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
    - name: Deploy-on-Heroku
      env:
        HEROKU_API_TOKEN: '0fd42d20-c6e4-4a49-afe8-24c0f4d690c0'
        HEROKU_APP_NAME: 'thecoolibrary'
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
