name: CI

on: push

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        brew install pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
