name: CI

on: push

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        sudo apt install software-properties-common python-software-properties
        sudo add-apt-repository ppa:pypa/ppa
        sudo apt update
        sudo apt install pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
