name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        export PATH="${HOME}/.local/bin:$PATH"
        python3 -m pip install --user pip
        python3 -m pip install --user pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3.7 manage.py makemigrations
        pipenv run python3.7 manage.py migrate
    - name: Test
      run: |
        pipenv run python3.7 manage.py test     
