name: CI

on: push

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        echo 'export PATH="${HOME}/.local/bin:$PATH"' >> ~/.bashrc
        sudo apt install python3-pip
        python3 -m pip install --user pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
