name: CI

on:
  push:
    paths-ignore: 
    - '**.yml'
    branches-ignore: 
      - refs/tags/*


jobs:
  build:
    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        pip install pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
