name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        sudo -H pip install -U pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Test
      run: |
        pipenv run python3 manage.py test     
